const bossesL = { img: 'img/common/Bosses.webp', x: 4, y: 4, zone: 'ruins' };

const bosses = {
  ruins: {
    necromancer_1: { large: false, index: 19, ...darkestS, zone: 'ruins' },
    necromancer_2: { large: false, index: 20, ...darkestS, zone: 'ruins' },
    necromancer_3: { large: false, index: 21, ...darkestS, zone: 'ruins' },
    prophet_1: { large: true, actions: 3, index: 0, ...original('prophet'), zone: 'ruins' },
    prophet_2: { large: true, actions: 3, index: 1, ...bossesL },
    prophet_3: { large: true, actions: 3, index: 2, ...bossesL },
    fanatic_1: { large: true, actions: 3, index: 3, ...original('fanatic'), zone: 'ruins' },
    fanatic_2: { large: true, actions: 3, index: 4, ...bossesL },
    fanatic_3: { large: true, actions: 3, index: 5, ...bossesL },
    pire_1: { large: true, index: 6, ...original('pire'), zone: 'ruins' },
    pire_2: { large: true, index: 7, ...bossesL },
    pire_3: { large: true, index: 8, ...bossesL },
    collector_1: { large: false, index: 22, ...darkestS, zone: 'ruins' },
    collector_2: { large: false, index: 23, ...darkestS, zone: 'ruins' },
    collector_3: { large: false, index: 24, ...darkestS, zone: 'ruins' },
    collected_highwayman_1: { large: false, index: 25, ...darkestS, zone: 'ruins' },
    collected_highwayman_2: { large: false, index: 26, ...darkestS, zone: 'ruins' },
    collected_highwayman_3: { large: false, index: 27, ...darkestS, zone: 'ruins' },
    collected_man_at_arms_1: { large: false, index: 28, ...darkestS, zone: 'ruins' },
    collected_man_at_arms_2: { large: false, index: 29, ...darkestS, zone: 'ruins' },
    collected_man_at_arms_3: { large: false, index: 30, ...darkestS, zone: 'ruins' },
    collected_vestal_1: { large: false, index: 31, ...darkestS, zone: 'ruins' },
    collected_vestal_2: { large: false, index: 32, ...darkestS, zone: 'ruins' },
    collected_vestal_3: { large: false, index: 33, ...darkestS, zone: 'ruins' },
  },

  courtyard: {
    countess_1: { large: true, actions: 3, index: 1, ...crimsonL },
    countess_2: { large: true, actions: 3, index: 2, ...crimsonL },
    countess_3: { large: true, actions: 3, index: 3, ...crimsonL },
    viscount_1: { large: false, actions: 3, index: 22, ...crimsonS },
    viscount_2: { large: false, actions: 3, index: 23, ...crimsonS },
    viscount_3: { large: false, actions: 3, index: 24, ...crimsonS },
    emaciated_body_1: { large: false, index: 25, ...crimsonS },
    emaciated_body_2: { large: false, index: 26, ...crimsonS },
    emaciated_body_3: { large: false, index: 27, ...crimsonS },
    body_1: { large: false, index: 28, ...crimsonS },
    body_2: { large: false, index: 29, ...crimsonS },
    body_3: { large: false, index: 30, ...crimsonS },
    bloodstuffed_body_1: { large: false, index: 31, ...crimsonS },
    bloodstuffed_body_2: { large: false, index: 32, ...crimsonS },
    bloodstuffed_body_3: { large: false, index: 33, ...crimsonS },
    garden_guardian_1: { large: true, actions: 2, index: 4, ...crimsonL },
    garden_guardian_2: { large: true, actions: 2, index: 5, ...crimsonL },
    garden_guardian_3: { large: true, actions: 2, index: 6, ...crimsonL },
    blood_fount_1: { large: false, index: 34, ...crimsonS },
    blood_fount_2: { large: false, index: 35, ...crimsonS },
    blood_fount_3: { large: false, index: 36, ...crimsonS },
    stone_shield_1: { large: false, index: 37, ...crimsonS },
    stone_shield_2: { large: false, index: 38, ...crimsonS },
    stone_shield_3: { large: false, index: 39, ...crimsonS },
    baron_1: { large: false, actions: 4, index: 40, ...crimsonS },
    baron_2: { large: false, actions: 4, index: 41, ...crimsonS },
    baron_3: { large: false, actions: 4, index: 42, ...crimsonS },
  },

  cove: {
    shambler_1: { large: true, index: 2, ...coveL },
    shambler_2: { large: true, index: 3, ...coveL },
    shambler_3: { large: true, index: 4, ...coveL },
    shambler_tentacle_1: { large: false, index: 22, ...coveS },
    shambler_tentacle_2: { large: false, index: 24, ...coveS },
    shambler_tentacle_3: { large: false, index: 26, ...coveS },
    siren_1: { large: true, actions: 2, index: 5, ...coveL },
    siren_2: { large: true, actions: 2, index: 6, ...coveL },
    siren_3: { large: true, actions: 2, index: 7, ...coveL },
    drowned_crew_1: { large: true, actions: 2, index: 8, ...coveL },
    drowned_crew_2: { large: true, actions: 2, index: 9, ...coveL },
    drowned_crew_3: { large: true, actions: 2, index: 10, ...coveL },
    drowned_anchorman_1: { large: false, index: 28, ...coveS },
    drowned_anchorman_2: { large: false, index: 29, ...coveS },
    drowned_anchorman_3: { large: false, index: 30, ...coveS },
  },

  warrens: {
    brigan_vvulf_1: { large: true, actions: 2, index: 1, ...warrensL },
    brigan_vvulf_2: { large: true, actions: 2, index: 2, ...warrensL },
    brigan_vvulf_3: { large: true, actions: 2, index: 3, ...warrensL },
    swine_prince_1: { large: true, actions: 2, index: 4, ...warrensL },
    swine_prince_2: { large: true, actions: 2, index: 5, ...warrensL },
    swine_prince_3: { large: true, actions: 2, index: 6, ...warrensL },
    wilbur_1: { large: false, index: 19, ...warrensS },
    wilbur_2: { large: false, index: 20, ...warrensS },
    wilbur_3: { large: false, index: 21, ...warrensS },
    'flesh_(head)_1': { large: false, index: 22, ...warrensS },
    'flesh_(head)_2': { large: false, index: 23, ...warrensS },
    'flesh_(head)_3': { large: false, index: 24, ...warrensS },
    'flesh_(bone)_1': { large: false, index: 25, ...warrensS },
    'flesh_(bone)_2': { large: false, index: 26, ...warrensS },
    'flesh_(bone)_3': { large: false, index: 27, ...warrensS },
    'flesh_(heart)_1': { large: false, index: 28, ...warrensS },
    'flesh_(heart)_2': { large: false, index: 29, ...warrensS },
    'flesh_(heart)_3': { large: false, index: 30, ...warrensS },
    'flesh_(butt)_1': { large: false, index: 31, ...warrensS },
    'flesh_(butt)_2': { large: false, index: 32, ...warrensS },
    'flesh_(butt)_3': { large: false, index: 33, ...warrensS },
  },

  darkest_dungeon: {
    templar_warlord: { large: true, actions: 2, index: 9, ...bossesL, zone: 'darkest' },
    templar_impaler: { large: true, actions: 2, index: 10, ...bossesL, zone: 'darkest' },
    mammoth_cyst: { large: true, actions: 2, index: 11, ...bossesL, zone: 'darkest' },
    white_cell_stalk: { large: false, actions: 2, index: 34, ...darkestS },
    shuffling_horror: { large: true, actions: 2, index: 12, ...bossesL, zone: 'darkest' },

    ancestor_1st_form: { large: false, actions: 4, index: 35, ...darkestS },
    perfect_reflection: { large: false, index: 36, ...darkestS },
    imperfect_reflection: { large: false, index: 39, ...darkestS },
    ancestor_2nd_form: { large: true, actions: 2, index: 13, ...bossesL, zone: 'darkest' },
    gestating_heart: { large: true, index: 14, ...bossesL, zone: 'darkest' },
    heart_of_darkness: { large: true, actions: 2, index: 15, ...bossesL, zone: 'darkest' },
  },
};

const allBosses = Object.values(bosses).reduce((acc, zone) => ({ ...acc, ...zone }), {});
