const bossesL = { img: 'img/common/Bosses.webp', x: 4, y: 4, zone: 'ruins' };

const bosses = {
  ruins: {
    necromancer_1: { large: true, index: 19, ...darkestS, zone: 'ruins' },
    necromancer_2: { large: true, index: 19 + 1, ...darkestS, zone: 'ruins' },
    necromancer_3: { large: true, index: 19 + 2, ...darkestS, zone: 'ruins' },
    prophet_1: { large: true, index: 0, ...bossesL },
    prophet_2: { large: true, index: 0 + 1, ...bossesL },
    prophet_3: { large: true, index: 0 + 2, ...bossesL },
    fanatic_1: { large: true, index: 3, ...bossesL },
    fanatic_2: { large: true, index: 3 + 1, ...bossesL },
    fanatic_3: { large: true, index: 3 + 2, ...bossesL },
    pire_1: { large: true, index: 6, ...bossesL },
    pire_2: { large: true, index: 6 + 1, ...bossesL },
    pire_3: { large: true, index: 6 + 2, ...bossesL },
    collector_1: { large: false, index: 22, ...darkestS, zone: 'ruins' },
    collector_2: { large: false, index: 22 + 1, ...darkestS, zone: 'ruins' },
    collector_3: { large: false, index: 22 + 2, ...darkestS, zone: 'ruins' },
    collected_highwayman_1: { large: false, index: 25, ...darkestS, zone: 'ruins' },
    collected_highwayman_2: { large: false, index: 25 + 1, ...darkestS, zone: 'ruins' },
    collected_highwayman_3: { large: false, index: 25 + 2, ...darkestS, zone: 'ruins' },
    collected_man_at_arms_1: { large: false, index: 28, ...darkestS, zone: 'ruins' },
    collected_man_at_arms_2: { large: false, index: 28 + 1, ...darkestS, zone: 'ruins' },
    collected_man_at_arms_3: { large: false, index: 28 + 2, ...darkestS, zone: 'ruins' },
    collected_vestal_1: { large: false, index: 31, ...darkestS, zone: 'ruins' },
    collected_vestal_2: { large: false, index: 31 + 1, ...darkestS, zone: 'ruins' },
    collected_vestal_3: { large: false, index: 31 + 2, ...darkestS, zone: 'ruins' },
  },

  courtyard: {
    countess_1: { large: true, index: 1, ...crimsonL },
    countess_2: { large: true, index: 1 + 1, ...crimsonL },
    countess_3: { large: true, index: 1 + 2, ...crimsonL },
    viscount_1: { large: false, index: 22, ...crimsonS },
    viscount_2: { large: false, index: 22 + 1, ...crimsonS },
    viscount_3: { large: false, index: 22 + 2, ...crimsonS },
    emaciated_body_1: { large: false, index: 25, ...crimsonS },
    emaciated_body_2: { large: false, index: 25 + 1, ...crimsonS },
    emaciated_body_3: { large: false, index: 25 + 2, ...crimsonS },
    body_1: { large: false, index: 28, ...crimsonS },
    body_2: { large: false, index: 28 + 1, ...crimsonS },
    body_3: { large: false, index: 28 + 2, ...crimsonS },
    bloodstuffed_body_1: { large: false, index: 31, ...crimsonS },
    bloodstuffed_body_2: { large: false, index: 31 + 1, ...crimsonS },
    bloodstuffed_body_3: { large: false, index: 31 + 2, ...crimsonS },
    garden_guardian_1: { large: true, index: 4, ...crimsonL },
    garden_guardian_2: { large: true, index: 4 + 1, ...crimsonL },
    garden_guardian_3: { large: true, index: 4 + 2, ...crimsonL },
    blood_fount_1: { large: false, index: 34, ...crimsonS },
    blood_fount_2: { large: false, index: 34 + 1, ...crimsonS },
    blood_fount_3: { large: false, index: 34 + 2, ...crimsonS },
    stone_shield_1: { large: false, index: 37, ...crimsonS },
    stone_shield_2: { large: false, index: 37 + 1, ...crimsonS },
    stone_shield_3: { large: false, index: 37 + 2, ...crimsonS },
    baron_1: { large: false, index: 40, ...crimsonS },
    baron_2: { large: false, index: 40 + 1, ...crimsonS },
    baron_3: { large: false, index: 40 + 2, ...crimsonS },
  },

  cove: {
    shambler_1: { large: true, index: 2, ...coveL },
    shambler_2: { large: true, index: 2 + 1, ...coveL },
    shambler_3: { large: true, index: 2 + 2, ...coveL },
    shambler_tentacle_1: { large: false, index: 22, ...coveS },
    shambler_tentacle_2: { large: false, index: 22 + 2, ...coveS },
    shambler_tentacle_3: { large: false, index: 22 + 4, ...coveS },
    siren_1: { large: true, index: 5, ...coveL },
    siren_2: { large: true, index: 5 + 1, ...coveL },
    siren_3: { large: true, index: 5 + 2, ...coveL },
    drowned_crew_1: { large: true, index: 8, ...coveL },
    drowned_crew_2: { large: true, index: 8 + 1, ...coveL },
    drowned_crew_3: { large: true, index: 8 + 2, ...coveL },
    drowned_anchorman_1: { large: false, index: 28, ...coveS },
    drowned_anchorman_2: { large: false, index: 28 + 1, ...coveS },
    drowned_anchorman_3: { large: false, index: 28 + 2, ...coveS },
  },

  warrens: {
    brigan_vvulf_1: { large: true, index: 1, ...warrensL },
    brigan_vvulf_2: { large: true, index: 1 + 1, ...warrensL },
    brigan_vvulf_3: { large: true, index: 1 + 2, ...warrensL },
    swine_prince_1: { large: true, index: 4, ...warrensL },
    swine_prince_2: { large: true, index: 4 + 1, ...warrensL },
    swine_prince_3: { large: true, index: 4 + 2, ...warrensL },
    wilbur_1: { large: false, index: 19, ...warrensS },
    wilbur_2: { large: false, index: 19 + 1, ...warrensS },
    wilbur_3: { large: false, index: 19 + 2, ...warrensS },
    'flesh_(head)_1': { large: false, index: 22, ...warrensS },
    'flesh_(head)_2': { large: false, index: 22 + 1, ...warrensS },
    'flesh_(head)_3': { large: false, index: 22 + 2, ...warrensS },
    'flesh_(bone)_1': { large: false, index: 25, ...warrensS },
    'flesh_(bone)_2': { large: false, index: 25 + 1, ...warrensS },
    'flesh_(bone)_3': { large: false, index: 25 + 2, ...warrensS },
    'flesh_(heart)_1': { large: false, index: 28, ...warrensS },
    'flesh_(heart)_2': { large: false, index: 28 + 1, ...warrensS },
    'flesh_(heart)_3': { large: false, index: 28 + 2, ...warrensS },
    'flesh_(butt)_1': { large: false, index: 31, ...warrensS },
    'flesh_(butt)_2': { large: false, index: 31 + 1, ...warrensS },
    'flesh_(butt)_3': { large: false, index: 31 + 2, ...warrensS },
  },

  darkest_dungeon: {
    templar_warlord: { large: true, index: 9, ...bossesL, zone: 'darkest' },
    templar_impaler: { large: true, index: 10, ...bossesL, zone: 'darkest' },
    mammoth_cyst: { large: true, index: 11, ...bossesL, zone: 'darkest' },
    white_cell_stalk: { large: false, index: 34, ...darkestS },
    shuffling_horror: { large: true, index: 12, ...bossesL, zone: 'darkest' },

    ancestor_1st_form: { large: false, index: 35, ...darkestS },
    perfect_reflection: { large: false, index: 36, ...darkestS },
    imperfect_reflection: { large: false, index: 39, ...darkestS },
    ancestor_2nd_form: { large: true, index: 13, ...bossesL, zone: 'darkest' },
    gestating_heart: { large: true, index: 14, ...bossesL, zone: 'darkest' },
    heart_of_darkness: { large: true, index: 15, ...bossesL, zone: 'darkest' },
  },
};

const allBosses = Object.values(bosses).reduce((acc, zone) => ({ ...acc, ...zone }), {});
