const conditions = [
  'bleed1',
  'bleed2',
  'bleed3',
  'bleed4',
  'blight1',
  'blight2',
  'blight3',
  'blight4',
  'buff',
  'debuff',
  'guard',
  'mark',
  'protection',
  'riposte',
  'stun',
];

const allMonsters = {
  ...ruins,
  ...courtyard,
  ...cove,
  ...warrens,
  ...common,
  ...darkest_dungeon,
  ...allBosses,
};
const zones = {
  ruins,
  courtyard,
  cove,
  warrens,
  common,
  darkest_dungeon,
};

const videos = {
  'None': '',
  'The Hamlet': '09u0rZJ0WEs',
  'Explore the Ruins': '1gryP9yJm7U',
  'Combat in the Ruins': 'Lxhvesbwz3E',
  'Camp Theme': 'rkL4_VKpyFQ',
  'Return to the Warrens': 'uGIK6dAe2Ko',
  'Battle in the Warrens': 'SVHwaYU1W5Q',
  'Mournweald Encounter': 'iv_m90xRzaM',
  'Terror and Madness': '0tpSUB4Q79c',
  'House of Ruin': 'BvKI-UxJTCQ',
  'Cove Battle': 'KRQYHh8xlEw',
  'Cove Battle - Siren': 'FaZI8C_4OSA',
  'The Final Combat': 'aXGVMaBY3UA',
  'Town in Chaos': 'OlRbc7fVDfA',
  'The Crimson Court': 'AROre7vM20s',
  'Circus Lobby': 'Bo6biyoRKIo',
  'Circus Combat': 'WBNeY6f4Qfo',
  'The Blasted Heath': 'i9yXl6km6X8',
  'Dark Mitochondria': 'BIv2dABhwZE',
  'The Senescence': 'WhVix2wgDD4',
  'Chloroplast of Cosmarium': '9-TRMlnVvYU',
  'All Things Must Come': 'E7JzX4CHJYg',
};
