const conditions = [
  "bleed1",
  "bleed2",
  "bleed3",
  "bleed4",
  "blight1",
  "blight2",
  "blight3",
  "blight4",
  "buff",
  "debuff",
  "guard",
  "mark",
  "protection",
  "riposte",
  "stun",
];

const commonSmall = { img: "original_img/common/monsters.png", x: 10, y: 7 };
const frenchSmall = { img: "original_img/common/monsters.jpg", x: 10, y: 7 };
const frenchBig = { img: "original_img/common/big.jpg", x: 2, y: 2 };

const common = {
  cultist_brawler: {
    level: 1,
    front: true,
    large: false,
    index: 18,
    ...commonSmall,
  },
  cultist_acolyte: {
    level: 1,
    front: false,
    large: false,
    index: 21,
    ...commonSmall,
  },
  brigand_cutthroat: {
    level: 1,
    front: true,
    large: false,
    index: 24,
    ...commonSmall,
  },
  brigand_fusilier: {
    level: 1,
    front: false,
    large: false,
    index: 27,
    ...commonSmall,
  },
  brigand_bloodletter: {
    level: 1,
    front: true,
    large: true,
    index: 0,
    img: "original_img/common/bloodletter.jpg",
    x: 1,
    y: 1,
  },
  maggot: { level: 1, front: true, large: false, index: 31, ...commonSmall },
  webber: { level: 1, front: false, large: false, index: 34, ...commonSmall },
  spitter: { level: 1, front: false, large: false, index: 37, ...commonSmall },
  bone_rabble: { level: 1, front: true, large: false, index: 40, ...commonSmall },
  madman: { level: 1, front: false, large: false, index: 43, ...commonSmall },
  pliskin: { level: 1, front: true, large: false, index: 46, ...commonSmall },
  ghoul: {
    level: 2,
    front: true,
    large: true,
    index: 0,
    img: "original_img/common/ghoul.jpg",
    x: 1,
    y: 1,
  },
  gargoyle: {
    level: 2,
    front: true,
    large: false,
    index: 0,
    img: "original_img/common/gargoyle.jpg",
    x: 1,
    y: 1,
  },
  rattler: {
    level: 2,
    front: true,
    large: false,
    index: 0,
    img: "original_img/common/rattler.jpg",
    x: 1,
    y: 1,
  },
  brigand_raider: {
    level: 3,
    front: true,
    large: false,
    index: 56,
    ...frenchSmall,
  },
  brigand_hunter: {
    level: 3,
    front: false,
    large: false,
    index: 59,
    ...frenchSmall,
  },
  adler: { level: 3, front: true, large: true, index: 3, ...frenchBig },
};
